CREATE TABLE [dbo].[Country]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Country] NVARCHAR(500) UNIQUE NOT NULL, 
    [Slug] NVARCHAR(500) UNIQUE NOT NULL, 
    [Code] NVARCHAR(10) UNIQUE NOT NULL
)
